// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBxjaddsg1JPyzylmnuDVWfoKWAanVEw',
    appId: '1:875477389978:web:697d2106e56678cae00523',
    messagingSenderId: '875477389978',
    projectId: 'final-project-23195',
    authDomain: 'final-project-23195.firebaseapp.com',
    storageBucket: 'final-project-23195.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCk_m-uVMKqoADfWYPHDZQzil-3d6a84',
    appId: '1:875477389978:android:45c08dbd2722a68fe00523',
    messagingSenderId: '875477389978',
    projectId: 'final-project-23195',
    storageBucket: 'final-project-23195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHnroSeRuKuK0hcCyx9fFyA5q9YL5QcO4',
    appId: '1:875477389978:ios:3fca7770ba4e1113e00523',
    messagingSenderId: '875477389978',
    projectId: 'final-project-23195',
    storageBucket: 'final-project-23195.appspot.com',
    iosBundleId: 'com.example.rideease1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHnroSeRuKuK0hcCyx9fFyA5q9YL5QcO4',
    appId: '1:875477389978:ios:3fca7770ba4e1113e00523',
    messagingSenderId: '875477389978',
    projectId: 'final-project-23195',
    storageBucket: 'final-project-23195.appspot.com',
    iosBundleId: 'com.example.rideease1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgQMTB7ajCdCgRL-0tkagPO-eaLKA3bAg',
    appId: '1:875477389978:web:b0970648f548aa46e00523',
    messagingSenderId: '875477389978',
    projectId: 'final-project-23195',
    authDomain: 'final-project-23195.firebaseapp.com',
    storageBucket: 'final-project-23195.appspot.com',
  );
}
